/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eAccident;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author goodman
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    Border white_border = BorderFactory.createMatteBorder(1,1,1,1, new Color(0,102,153));
    Border default_border = BorderFactory.createMatteBorder(1,1,1,1, new Color(204,204,204));
    
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cancel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        next = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        firstField = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        regionField = new javax.swing.JComboBox<String>();
        jLabel58 = new javax.swing.JLabel();
        maleField = new javax.swing.JRadioButton();
        femaleField = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        firstField1 = new javax.swing.JTextField();
        firstField2 = new javax.swing.JTextField();
        firstField3 = new javax.swing.JTextField();
        regionField1 = new javax.swing.JComboBox<String>();
        max = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        close = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        min = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        allofficers = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 129, 181)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cancel");
        cancel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 110, 20));

        jPanel7.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 120, 30));

        next.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextMouseExited(evt);
            }
        });
        next.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Next >");
        next.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 110, 20));

        jPanel7.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 140, 30));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 642, 1100, 80));

        jLabel10.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("Well, System users!");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 207, -1));

        jLabel11.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jLabel11.setText("Click \"Next\" to Add more officers in the System or \"Cancel\" to exit if you are done");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, 670, 30));

        jLabel12.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jLabel12.setText("You can add the details of the Officers, including their passwords. Please remember the integrity of the data of the officers.");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 860, 30));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 102, 153));
        jLabel41.setText("Last Name :");
        jPanel10.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 96, 110, 23));

        jLabel42.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 102, 153));
        jLabel42.setText("First Name :");
        jPanel10.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 36, 110, 23));

        jLabel43.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 102, 153));
        jLabel43.setText("Designation :");
        jPanel10.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 152, 110, 23));

        jLabel44.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 102, 153));
        jLabel44.setText("Numbers :");
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 221, 110, 23));

        jLabel45.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 102, 153));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Gender");
        jPanel10.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 110, 23));

        firstField.setBackground(new java.awt.Color(197, 227, 247));
        firstField.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        firstField.setForeground(new java.awt.Color(0, 51, 51));
        firstField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        firstField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstFieldActionPerformed(evt);
            }
        });
        jPanel10.add(firstField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 220, 30));
        jPanel10.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 260, 10));
        jPanel10.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 260, 10));
        jPanel10.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 260, 10));
        jPanel10.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 260, 10));

        regionField.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        regionField.setForeground(new java.awt.Color(0, 102, 153));
        regionField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mbarara", "Abim", "Apac", "Arua", "Entebbe", "Fort Portal", "Hoima", "Nebbi", "Masind", "Gulu", "Omoro", "Kampala", "Wakiso", "Mukono", "Mbarara", "Mbale", "Kitgum", "", "", "" }));
        regionField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 216, 216)));
        regionField.setOpaque(false);
        jPanel10.add(regionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 140, -1));

        jLabel58.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 102, 153));
        jLabel58.setText("District :");
        jPanel10.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 295, 110, 23));

        maleField.setBackground(new java.awt.Color(197, 227, 247));
        buttonGroup1.add(maleField);
        maleField.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        maleField.setForeground(new java.awt.Color(0, 102, 153));
        maleField.setText("Male");
        jPanel10.add(maleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, -1, -1));

        femaleField.setBackground(new java.awt.Color(197, 227, 247));
        buttonGroup1.add(femaleField);
        femaleField.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        femaleField.setForeground(new java.awt.Color(0, 102, 153));
        femaleField.setText("Female");
        jPanel10.add(femaleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(false);
        jPanel10.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 80, 30));

        firstField1.setBackground(new java.awt.Color(197, 227, 247));
        firstField1.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        firstField1.setForeground(new java.awt.Color(0, 51, 51));
        firstField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jPanel10.add(firstField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 220, 30));

        firstField2.setBackground(new java.awt.Color(197, 227, 247));
        firstField2.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        firstField2.setForeground(new java.awt.Color(0, 51, 51));
        firstField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        jPanel10.add(firstField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 220, 30));

        firstField3.setBackground(new java.awt.Color(197, 227, 247));
        firstField3.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        firstField3.setForeground(new java.awt.Color(0, 51, 51));
        firstField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        firstField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstField3ActionPerformed(evt);
            }
        });
        jPanel10.add(firstField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 220, 30));

        regionField1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        regionField1.setForeground(new java.awt.Color(0, 102, 153));
        regionField1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Western", "Northern", "Central", "Eastern", "Mid-Western", "West Nile" }));
        regionField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 216, 216)));
        regionField1.setOpaque(false);
        jPanel10.add(regionField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 140, -1));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 920, 390));

        max.setBackground(new java.awt.Color(255, 255, 255));
        max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxMouseExited(evt);
            }
        });
        max.setLayout(null);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_minus_15px.png"))); // NOI18N
        max.add(jLabel13);
        jLabel13.setBounds(10, 5, 30, 15);

        jPanel6.add(max, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 50, 30));

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        close.setLayout(null);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_15px.png"))); // NOI18N
        close.add(jLabel14);
        jLabel14.setBounds(10, 5, 20, 15);

        jPanel6.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 50, 30));

        min.setBackground(new java.awt.Color(255, 255, 255));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minMouseExited(evt);
            }
        });
        min.setLayout(null);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_rectangle_15px.png"))); // NOI18N
        min.add(jLabel15);
        jLabel15.setBounds(10, 5, 30, 15);

        jPanel6.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 50, 30));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_sick_25px.png"))); // NOI18N
        jLabel2.setText(" Accident Management System");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 40));

        allofficers.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        allofficers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allofficersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                allofficersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                allofficersMouseExited(evt);
            }
        });
        allofficers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("All System Users");
        allofficers.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 20));

        jPanel6.add(allofficers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 158, 39));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstFieldActionPerformed

    private void firstField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstField3ActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        changeColor(close, new Color(204,3,6));
        
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        changeColor(close, new Color(255,255,255));
    }//GEN-LAST:event_closeMouseExited

    private void minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseEntered
        changeColor(min, new Color(204,204,255));
    }//GEN-LAST:event_minMouseEntered

    private void minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseExited
        changeColor(min, new Color(255,255,255));
    }//GEN-LAST:event_minMouseExited

    private void maxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseEntered
        changeColor(max, new Color(204,204,255));
    }//GEN-LAST:event_maxMouseEntered

    private void maxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxMouseExited
        changeColor(max, new Color(255,255,255));
    }//GEN-LAST:event_maxMouseExited

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        try {                                  
            String RESULT="ACCOUNTING_AND_FINANCE_STUDENTS.pdf";
            
            Document document=new Document (PageSize.A5.rotate());
            try {
                PdfWriter.getInstance(document, new FileOutputStream(RESULT));//Need to write in a table
            } catch (DocumentException ex) {
                
            } catch (FileNotFoundException ex) {
                
            }
            
            document.open();
            
            PdfPTable table = new PdfPTable(3);//create table with 2 columns
            
            
            table.addCell("REG_NUMBER");
            table.addCell("FIRST_NAME");
            table.addCell("LAST_NAME");
            //table.addCell("age");
            
            /*table.addCell("REGISTRATION_NUMBER");
            table.addCell(rs.getString("FIRST_NAME"));
            table.addCell(rs.getString("LAST_NAME"));
            //table.addCell(rs.getString("age"));*/
            
            document.add(table);
            document.close();
            
            
            
            if(Desktop.isDesktopSupported()){
                try{
                    File myfile = new File("ACCOUNTING_AND_FINANCE_STUDENTS.pdf");
                    Desktop.getDesktop().open(myfile);
                }
                catch(IOException ex){}
            }
            document.close();//close a pdf document
            
        } catch (DocumentException ex) {
            Logger.getLogger(AdminDashboard.class.getName()).log(Level.SEVERE, null, ex);

        }
       
          
       
    }//GEN-LAST:event_nextMouseClicked

    private void nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseEntered
        next.setBorder(white_border);
    }//GEN-LAST:event_nextMouseEntered

    private void nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseExited
        next.setBorder(default_border);
    }//GEN-LAST:event_nextMouseExited

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setBorder(white_border);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setBorder(default_border);
    }//GEN-LAST:event_cancelMouseExited

    private void allofficersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allofficersMouseClicked
        try{
            Class.forName("com.mysql.jdbc.Driver"); //register the driver
            conn = DriverManager.getConnection("jdbc:mysql://localhost/accident","rogers","rogers81");
            stmt = conn.createStatement();

            String result = "policeofficers.pdf";

            Document doc = new Document(PageSize.A4.rotate());

            try{
                PdfWriter.getInstance(doc, new FileOutputStream(result));

            }
            catch(DocumentException ex){
                ex.printStackTrace();
                //Logger.getLogger(Prisoner.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch(FileNotFoundException ex){
                ex.printStackTrace();
            }

            doc.open();

            Paragraph para = new Paragraph("Uganda Police\nDepartment of Traffic officers",FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24));
            /*
            para.setSpacingAfter(20);
            para.setIndentationLeft(200);

            Paragraph pr = new Paragraph("[PIMS]");
            pr.setIndentationLeft(20);
            */

            para.setSpacingAfter(15);
            para.setSpacingBefore(15);
            para.setIndentationLeft(200);

            //String source = "C:\\Users\\DELL i5\\Desktop\\jCal\\pimsLogo4.jpeg";
            //String src = "C:\\Users\\DELL i5\\Documents\\NetBeansProjects\\PrisonersInformationManagementSystem\\src\\prisonersInfo\\Images\\pimsLogo4.jpeg";
            /*String src2 = "C:\\Users\\DELL i5\\Documents\\NetBeansProjects\\PrisonersInformationManagementSystem\\src\\prisonersInfo\\Images\\iconFinal2.PNG";
            Image img = Image.getInstance(src2);
            img.setIndentationLeft(130);
            */
            PdfPTable table = new PdfPTable(3);

            try{
                //query = "select * from Prisoner";
                //query = "select concat(fName,\" \",sName) as full_name,gender,age,cell_cell_id from prisoner;";
                String query = "select firstName,lastName,designation,officer_no,dob,gender from officer";
                rs = stmt.executeQuery(query);

                PdfPCell nmCell = new PdfPCell();
                Phrase pnm = new Phrase("First Name");
                pnm.setFont(FontFactory.getFont(FontFactory.HELVETICA_BOLD,15));
                nmCell.addElement(pnm);
                table.addCell(nmCell);
                /*
                PdfPCell genderCell = new PdfPCell();
                Phrase pgn = new Phrase("GENDER");
                pgn.setFont(FontFactory.getFont(FontFactory.HELVETICA_BOLD,15));
                genderCell.addElement(pgn);
                table.addCell(genderCell);
                */
                PdfPCell ageCell = new PdfPCell();
                Phrase age = new Phrase("Last Name");
                age.setFont(FontFactory.getFont(FontFactory.HELVETICA_BOLD,15));
                ageCell.addElement(age);
                table.addCell(ageCell);

                PdfPCell cidCell = new PdfPCell();
                Phrase cid = new Phrase("Designation");
                cid.setFont(FontFactory.getFont(FontFactory.HELVETICA_BOLD,15));
                cidCell.addElement(cid);
                table.addCell(cidCell);

                PdfPCell cidCel = new PdfPCell();
                Phrase ci = new Phrase("Officer Number");
                cid.setFont(FontFactory.getFont(FontFactory.HELVETICA_BOLD,15));
                cidCell.addElement(ci);
                table.addCell(cidCel);

                PdfPCell dobCell = new PdfPCell();
                Phrase dob = new Phrase("Date of Birth");
                age.setFont(FontFactory.getFont(FontFactory.HELVETICA_BOLD,15));
                ageCell.addElement(dob);
                table.addCell(dobCell);

                PdfPCell genderCell = new PdfPCell();
                Phrase gender = new Phrase("Gender");
                age.setFont(FontFactory.getFont(FontFactory.HELVETICA_BOLD,15));
                ageCell.addElement(gender);
                table.addCell(genderCell);

                while(rs.next()){
                    //table.addCell(rs.getString("prisoner_id"));
                    //table.addCell(rs.getString("fName"));
                    //table.addCell(rs.getString("sName"));

                    table.addCell(rs.getString("firstName"));
                    table.addCell(rs.getString("lastName"));
                    table.addCell(rs.getString("designation"));
                    table.addCell(rs.getString("officer_no"));
                    table.addCell(rs.getString("dob"));
                    table.addCell(rs.getString("gender"));
                }
                /*
                doc.add(pr);
                doc.add(img);
                doc.add(para);
                doc.add(table);

                PdfPTable footTable = new PdfPTable(1);
                PdfPCell footerCell = new PdfPCell();
                Phrase footer = new Phrase("Generated by Martin Ssendyowa");
                //footerCell.addElement(footer);
                footerCell.setPhrase(footer);
                footerCell.setBorder(0);
                footTable.addCell(footerCell);
                //footTable.setSpacingBefore(doc.bottom());
                footTable.setSpacingBefore(doc.bottomMargin());
                footTable.setHorizontalAlignment(90);
                */
                //doc.add(iconTable);
                //doc.add(img);

                Paragraph prline = new Paragraph("---------------------------------------------------------------------------------------",FontFactory.getFont(FontFactory.HELVETICA, 24));
                prline.setIndentationLeft(doc.leftMargin());
                prline.setIndentationRight(doc.rightMargin());
                doc.add(prline);

                doc.add(para);
                doc.add(table);
                //doc.addTitle("All Prisoners' Cases");

                //footer
                PdfPTable footTable = new PdfPTable(1);
                PdfPCell footerCell = new PdfPCell();
                Phrase footer = new Phrase("Kuyeso Rogers\nAlgo Codein 221");
                // automatically attach name depending on user login i.e can use login as inner class
                //add time and date when report is generated

                footerCell.setPhrase(footer);
                footerCell.setBorder(0);

                //Date gendate new Date();

                //Phrase gen = new Phrase("Date: " + gendate);
                PdfPCell footerCell2 = new PdfPCell();
                //footerCell2.addElement(gen);
                footerCell2.setBorder(0);
                //footTable.addCell(footerCell);
                //footTable.setSpacingBefore(doc.bottom());

                footTable.addCell(footerCell);
                footTable.addCell(footerCell2);

                footTable.setSpacingBefore(doc.bottomMargin());
                footTable.setHorizontalAlignment(100);
                footTable.setSpacingBefore(50);

                doc.add(footTable);

                doc.close();

                if(Desktop.isDesktopSupported()){
                    File fpdf = new File(result);
                    Desktop.getDesktop().open(fpdf);
                }

            }
            catch (SQLException ex) {
                ex.printStackTrace();
                //Logger.getLogger(Prisoner.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch (DocumentException ex) {
                ex.printStackTrace();
                //Logger.getLogger(Prisoner.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch (IOException ex) {
                ex.printStackTrace();
                //Logger.getLogger(Prisoner.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        catch(SQLException ex){
            ex.printStackTrace();
        }
        catch(ClassNotFoundException e){
            e.printStackTrace();
        }
        finally{
            try{
                if(stmt != null){
                    stmt.close();
                }
                if(conn != null){
                    conn.close();
                }
            }
            catch(SQLException ex){
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_allofficersMouseClicked

    private void allofficersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allofficersMouseEntered
        next.setBorder(white_border);
    }//GEN-LAST:event_allofficersMouseEntered

    private void allofficersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allofficersMouseExited
        next.setBorder(default_border);
    }//GEN-LAST:event_allofficersMouseExited

    /**
     * @param args the command line arguments
     */
    
    public void changeColor(JPanel hover, Color rand){
        hover.setBackground(rand);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allofficers;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cancel;
    private javax.swing.JPanel close;
    private javax.swing.JRadioButton femaleField;
    private javax.swing.JTextField firstField;
    private javax.swing.JTextField firstField1;
    private javax.swing.JTextField firstField2;
    private javax.swing.JTextField firstField3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton maleField;
    private javax.swing.JPanel max;
    private javax.swing.JPanel min;
    private javax.swing.JPanel next;
    private javax.swing.JComboBox<String> regionField;
    private javax.swing.JComboBox<String> regionField1;
    // End of variables declaration//GEN-END:variables
}
