/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */





package eAccident;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author goodMan
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepanel = new javax.swing.JPanel();
        image_label = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        accident = new javax.swing.JLabel();
        records = new javax.swing.JLabel();
        database = new javax.swing.JLabel();
        general = new javax.swing.JLabel();
        emergency = new javax.swing.JLabel();
        reacted = new javax.swing.JLabel();
        not_reacted = new javax.swing.JLabel();
        pending = new javax.swing.JLabel();
        common = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1350, 720));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(54, 33, 89));
        sidepanel.setMinimumSize(new java.awt.Dimension(300, 720));
        sidepanel.setPreferredSize(new java.awt.Dimension(300, 720));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image_label.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\profile2.png")); // NOI18N
        image_label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        sidepanel.add(image_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 100, 90));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(249, 246, 246));
        jLabel14.setText("Profile Information");
        sidepanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 160, 30));

        jPanel1.setBackground(new java.awt.Color(64, 43, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(85, 65, 118));
        home.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        home.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\home.png")); // NOI18N
        home.setText("  Home");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 250, 40));

        accident.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        accident.setForeground(new java.awt.Color(255, 255, 255));
        accident.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\total_accident.png")); // NOI18N
        accident.setText("  Total Accident");
        accident.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        accident.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        jPanel1.add(accident, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 40));

        records.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        records.setForeground(new java.awt.Color(255, 255, 255));
        records.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\record1.png")); // NOI18N
        records.setText("  Records");
        records.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        jPanel1.add(records, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 40));

        database.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        database.setForeground(new java.awt.Color(255, 255, 255));
        database.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\database.png")); // NOI18N
        database.setText("  View DataBase");
        database.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        jPanel1.add(database, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, 40));

        general.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        general.setForeground(new java.awt.Color(255, 255, 255));
        general.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\general.png")); // NOI18N
        general.setText("  General");
        general.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        jPanel1.add(general, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 40));

        emergency.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emergency.setForeground(new java.awt.Color(255, 255, 255));
        emergency.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\emergency.png")); // NOI18N
        emergency.setText("  Emergency");
        emergency.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        jPanel1.add(emergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 40));

        reacted.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reacted.setForeground(new java.awt.Color(255, 255, 255));
        reacted.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\done.png")); // NOI18N
        reacted.setText("  Incidence Reacted To");
        reacted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        jPanel1.add(reacted, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 250, 40));

        not_reacted.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        not_reacted.setForeground(new java.awt.Color(255, 255, 255));
        not_reacted.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\silent.png")); // NOI18N
        not_reacted.setText("  No Reaction Made");
        not_reacted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        jPanel1.add(not_reacted, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 40));

        pending.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pending.setForeground(new java.awt.Color(255, 255, 255));
        pending.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\pending.png")); // NOI18N
        pending.setText("  Pendind Issues");
        pending.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        jPanel1.add(pending, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, 40));

        common.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        common.setForeground(new java.awt.Color(255, 255, 255));
        common.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\common.png")); // NOI18N
        common.setText("  Common Issues");
        common.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                commonMousePressed(evt);
            }
        });
        jPanel1.add(common, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 250, 40));

        sidepanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 390));

        getContentPane().add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void commonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_commonMousePressed

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeMousePressed

    /**
     * @param args the command line arguments
     */
    private void jcommonMousePressed(java.awt.event.MouseEvent evt) {                                     
        resetColor(home);
        resetColor(accident);
        resetColor(records);
        resetColor(database);
        resetColor(general);
        resetColor(emergency);
        resetColor(reacted);
        resetColor(not_reacted);
        resetColor(pending);
        setColor(common);
    }                                    

    private void pendingMousePressed(java.awt.event.MouseEvent evt) {                                     
        resetColor(home);
        resetColor(accident);
        resetColor(records);
        resetColor(database);
        resetColor(general);
        resetColor(emergency);
        resetColor(reacted);
        resetColor(not_reacted);
        setColor(pending);
        resetColor(common);
    }                                    

    private void not_reactedMousePressed(java.awt.event.MouseEvent evt) {                                         
        resetColor(home);
        resetColor(accident);
        resetColor(records);
        resetColor(database);
        resetColor(general);
        resetColor(emergency);
        resetColor(reacted);
        setColor(not_reacted);
        resetColor(pending);
        resetColor(common);
    }                                        

    private void reactedMousePressed(java.awt.event.MouseEvent evt) {                                     
        resetColor(home);
        resetColor(accident);
        resetColor(records);
        resetColor(database);
        resetColor(general);
        resetColor(emergency);
        setColor(reacted);
        resetColor(not_reacted);
        resetColor(pending);
        resetColor(common);
    }                                    

    private void emergencyMousePressed(java.awt.event.MouseEvent evt) {                                       
        resetColor(home);
        resetColor(accident);
        resetColor(records);
        resetColor(database);
        resetColor(general);
        setColor(emergency);
        resetColor(reacted);
        resetColor(not_reacted);
        resetColor(pending);
        resetColor(common);
    }                                      

    private void generalMousePressed(java.awt.event.MouseEvent evt) {                                     
        resetColor(home);
        resetColor(accident);
        resetColor(records);
        resetColor(database);
        setColor(general);
        resetColor(emergency);
        resetColor(reacted);
        resetColor(not_reacted);
        resetColor(pending);
        resetColor(common);
    }                                    

    private void databaseMousePressed(java.awt.event.MouseEvent evt) {                                      
        resetColor(home);
        resetColor(accident);
        resetColor(records);
        setColor(database);
        resetColor(general);
        resetColor(emergency);
        resetColor(reacted);
        resetColor(not_reacted);
        resetColor(pending);
        resetColor(common);
    }                                     

    private void recordsMousePressed(java.awt.event.MouseEvent evt) {                                     
        resetColor(home);
        resetColor(accident);
        setColor(records);
        resetColor(database);
        resetColor(general);
        resetColor(emergency);
        resetColor(reacted);
        resetColor(not_reacted);
        resetColor(pending);
        resetColor(common);
    }                                    

    private void accidentMousePressed(java.awt.event.MouseEvent evt) {                                      
        resetColor(home);
        setColor(accident);
        resetColor(records);
        resetColor(database);
        resetColor(general);
        resetColor(emergency);
        resetColor(reacted);
        resetColor(not_reacted);
        resetColor(pending);
        resetColor(common);
    }                                     


    void setColor(JLabel panel){
        panel.setBackground(new Color(85,65,118));
        
    }
    
    void resetColor(JLabel panel){
        panel.setBackground(new Color(64,43,100));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accident;
    private javax.swing.JLabel common;
    private javax.swing.JLabel database;
    private javax.swing.JLabel emergency;
    private javax.swing.JLabel general;
    private javax.swing.JLabel home;
    private javax.swing.JLabel image_label;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel not_reacted;
    private javax.swing.JLabel pending;
    private javax.swing.JLabel reacted;
    private javax.swing.JLabel records;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}
