/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eAccident;

import java.awt.Container;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author goodMan
 */
public class Incidence extends javax.swing.JFrame {
    
    String filename;
    byte[] incidence_image;
    Connection con;
    PreparedStatement pstmt;
    String emergency;
   
    /**
     * Creates new form User_Data
     */
    public Incidence() {
        initComponents();
        this.incidence_image =null;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emergency_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        damagedField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        injuryField = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        noField = new javax.swing.JRadioButton();
        upload_button = new javax.swing.JButton();
        categoryField = new javax.swing.JComboBox<>();
        yesField = new javax.swing.JRadioButton();
        img_label = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(14, 14, 193));
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\eAccident-pro\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\Images\\close3.png")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 30, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("System");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 70, 50));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setText("Registration and Reporting");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, 50));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("e-Accident");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, 50));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 0, 0));
        jLabel22.setText("Incidence Detail");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 280, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 0, 0));
        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\e-Accident-Pro-Version\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\images\\icons8_sorting_18px_1.png")); // NOI18N
        jLabel23.setText("Category");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 0, 0));
        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\e-Accident-Pro-Version\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\images\\icons8_physical_therapy_18px.png")); // NOI18N
        jLabel24.setText(" Injury         ");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 0, 0));
        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\e-Accident-Pro-Version\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\images\\icons8_crashed_car_18px_1.png")); // NOI18N
        jLabel25.setText("Damaged Item");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 140, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 0, 0));
        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\e-Accident-Pro-Version\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\images\\icons8_picture_18px.png")); // NOI18N
        jLabel26.setText("Upload Picture");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, 30));

        damagedField.setForeground(new java.awt.Color(51, 0, 0));
        damagedField.setBorder(null);
        damagedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                damagedFieldActionPerformed(evt);
            }
        });
        jPanel7.add(damagedField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\e-Accident-Pro-Version\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\images\\line2_1.png")); // NOI18N
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 210, 30));

        jPanel3.setBackground(new java.awt.Color(51, 0, 0));
        jPanel3.setForeground(new java.awt.Color(51, 0, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\e-Accident-Pro-Version\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\images\\icons8_curved_arrow_25px_1.png")); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(51, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\e-Accident-Pro-Version\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\images\\icons8_reply_arrow_25px.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 420, 80));

        injuryField.setBackground(new java.awt.Color(51, 0, 0));
        injuryField.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        injuryField.setForeground(new java.awt.Color(255, 255, 255));
        injuryField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Severe Injuries", "People died", "Minor Injury", "Not Sure" }));
        injuryField.setToolTipText("");
        jPanel7.add(injuryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 210, 30));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 0, 0));
        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\e-Accident-Pro-Version\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\images\\icons8_ambulance_18px.png")); // NOI18N
        jLabel27.setText("Emergency");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, 30));

        noField.setBackground(new java.awt.Color(255, 255, 255));
        emergency_group.add(noField);
        noField.setForeground(new java.awt.Color(51, 0, 0));
        noField.setText(" NO");
        noField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noFieldActionPerformed(evt);
            }
        });
        jPanel7.add(noField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        upload_button.setBackground(new java.awt.Color(51, 0, 0));
        upload_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        upload_button.setForeground(new java.awt.Color(255, 255, 255));
        upload_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\goodMan\\Documents\\NetBeansProjects\\e-Accident-Pro-Version\\src\\main\\java\\com\\mycompany\\eaccident\\pro\\eAccident\\images\\icons8_upload_to_the_cloud_18px_2.png")); // NOI18N
        upload_button.setText("Upload");
        upload_button.setActionCommand("upload");
        upload_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_buttonActionPerformed(evt);
            }
        });
        jPanel7.add(upload_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, 30));

        categoryField.setBackground(new java.awt.Color(51, 0, 0));
        categoryField.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        categoryField.setForeground(new java.awt.Color(255, 255, 255));
        categoryField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car collided", "Car Catched Fire", "Car TurnedOver", "Someone knocked", "slipped off Road", "Broken Bridge", "Others" }));
        jPanel7.add(categoryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 210, 30));

        yesField.setBackground(new java.awt.Color(255, 255, 255));
        emergency_group.add(yesField);
        yesField.setForeground(new java.awt.Color(51, 0, 0));
        yesField.setText("  YES");
        yesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesFieldActionPerformed(evt);
            }
        });
        jPanel7.add(yesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        img_label.setBackground(new java.awt.Color(255, 255, 255));
        img_label.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel7.add(img_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 130, 100));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 420, 390));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Together We SAVE LIVES !");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 310, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        //dispose();
        //setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void damagedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_damagedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_damagedFieldActionPerformed

    private void noFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String category = categoryField.getSelectedItem().toString();
        String injury = injuryField.getSelectedItem().toString();
        String damaged = damagedField.getText();
        ImageIcon image = (ImageIcon) img_label.getIcon();
        //String emergency;
        yesField.setActionCommand("Emergency");
        noField.setActionCommand("Not Emergency");
        String emergency = emergency_group.getSelection().getActionCommand();
                //String emergency;

        if(yesField.isSelected()){
            emergency = "Emergency";
        }
        if(noField.isSelected()){
            emergency="Not Emergency";
        }
        if(!yesField.isSelected() && !noField.isSelected()){
            JOptionPane.showMessageDialog(this, "Please Select first");
        }
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/accident","rogers","rogers81");
            pstmt = con.prepareStatement("insert into incidence(category,injury,damaged,emergency,image,location_id) values(?,?,?,?,?,(select location_id from location WHERE location_id= (select MAX(location_id) from location)))");
            pstmt.setString(1, category);
            pstmt.setString(2, injury);
            pstmt.setString(3, damaged);
            pstmt.setString(4, emergency);
            //int image_data = Integer.parseInt(String.valueOf(image.length()));
            //incidence_image = new byte[image_data];
            pstmt.setBytes(5, incidence_image);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Recorded");
            con.close();
            
            }catch (ClassNotFoundException ex) {
            Logger.getLogger(Location_Detail.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Location_Detail.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        this.dispose();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Photos_of_Scence photo = new Photos_of_Scence();
        photo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void yesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesFieldActionPerformed

    private void upload_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_buttonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        
        
        ImageIcon imageIcon = new ImageIcon (new ImageIcon(filename).getImage().getScaledInstance(img_label.getWidth(), img_label.getHeight(),Image.SCALE_SMOOTH)); 
        img_label.setIcon(imageIcon);
        try{
            File image = new File(filename);
            
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum=fis.read(buf))!=-1;){
                bos.write(buf, 0, readNum);
                incidence_image = bos.toByteArray();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_upload_buttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Location_Detail detail = new Location_Detail();
        detail.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Incidence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoryField;
    private javax.swing.JTextField damagedField;
    private javax.swing.ButtonGroup emergency_group;
    private javax.swing.JLabel img_label;
    private javax.swing.JComboBox<String> injuryField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton noField;
    private javax.swing.JButton upload_button;
    private javax.swing.JRadioButton yesField;
    // End of variables declaration//GEN-END:variables
}
